baseURL = "https://christmas2021.blueboat.com.au/"
languageCode = "en-au"
title = "Summer tracks | Curated by Blueboat."

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# [taxonomies]
#   category = "categories"

disableFastRender = true

[params]
  description = "Turn up the volume. Sit back. Enjoy."
  images = ['Spotify_SocialShare_1200x627_V1-0.jpg']
  title = "Summer tracks | Curated by Blueboat."

[permalinks]
  posts = "/:section/:title/"